- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Start and Enable MySQL
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Ensure Root Password is Set
  ansible.builtin.shell: |
    mysql -uroot -p{{ mysql_root_password }} -e "QUIT" || \
    mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
  args:
    executable: /bin/bash
  register: root_pass_setup
  failed_when: false

- name: Allow Remote Connections
  ansible.builtin.lineinfile:
    path: /etc/my.cnf.d/mysql-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart MySQL

- name: Create Roboshop User
  ansible.builtin.shell: |
    mysql -uroot -p{{ mysql_root_password }} <<EOF
    CREATE USER IF NOT EXISTS 'roboshop'@'%' IDENTIFIED WITH mysql_native_password BY 'RoboShop@1';
    GRANT ALL PRIVILEGES ON *.* TO 'roboshop'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
    EOF
  args:
    executable: /bin/bash