- name: Import Node JS
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
  vars:
    component: catalogue

# ---------------- REPOSITORY SETUP ----------------
- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Shell (mongosh)
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

# ---------------- MongoDB data initialization ----------------
- name: Check if catalogue data already exists
  ansible.builtin.command: >
    mongosh --host mongod-dev.kiranpanchavati.online 
    --quiet --eval "db.getSiblingDB('catalogue').products.countDocuments()"
  register: catalogue_count
  changed_when: false
  ignore_errors: yes

- name: Load catalogue master data
  ansible.builtin.command: >
    mongosh --host mongod-dev.kiranpanchavati.online 
    < /app/db/master-data.js
  when: catalogue_count.stdout is defined and catalogue_count.stdout | int == 0

