####################################################################
# 2. Create roboshop user
####################################################################
- name: Create roboshop user
  ansible.builtin.user:
    name: roboshop
    create_home: yes

####################################################################
# 3. Copy Cart systemd service file
####################################################################
- name: Copy {{component}} systemd service file
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

####################################################################
# 4. Create /app directory
####################################################################
- name: Create /app directory
  ansible.builtin.file:
    path: /app
    state: directory
    owner: roboshop
    group: roboshop

#####################################################################
## 5. Download and extract {{component}}  application
#####################################################################
#- name: Download and extract {{component}}  application code
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip
#    dest: /app
#    remote_src: yes
#    owner: roboshop
#    group: roboshop

- name: Download {{component}} application code
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip"
    dest: "/tmp/{{component}}.zip"